---
- name: vm-01
  box: centos/7
  ip: 100.0.10.100
  mem: 2048
  cpu: 2
- name: vm-02
  box: centos/7
  ip: 100.0.10.101
  mem: 2048
  cpu: 2
- name: vm-03
  box: centos/7
  ip: 100.0.10.102
  mem: 2048
  cpu: 2
