# -*- mode: ruby -*-
# vim: set ft=ruby ts=2 et :

# Vagrant File tested in:
#
# CentOS Linux release 7.2.1511
#
# $ vagrant --version
# Vagrant 1.8.1
#
# $ vagrant plugin list
# vagrant-libvirt (0.0.35)

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# Require a recent version of vagrant otherwise some have reported errors 
# setting host names on boxes
Vagrant.require_version ">= 1.7.2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  vagrant_producers_config = {
    "box_name"  => ENV['BOX_NAME'] || "centos/7",
    "subscription_register"  => ENV['SUB_REG'],
    "subscription_user"  => ENV['SUB_USER'],
    "subscription_pass"  => ENV['SUB_PASS'],
    "num_nodes" => ENV['NUM_HOSTS'] || 2,
    "node_memory"  => ENV['NODE_MEMORY'] || 512,
  }

  config.vm.box = vagrant_cluster_config["box_name"]

  # NOTE: vagrant-registration (1.3.0) is not working for me
  
  if Vagrant.has_plugin?('vagrant-registration')
     # enable or disable registration step.
     config.registration.skip = vagrant_cluster_config["subscription_register"]
     config.registration.skip = true
  #  config.registration.username = vagrant_cluster_config["subscription_user"] 
  #  config.registration.password = vagrant_cluster_config["subscription_pass"] 
     # disables automatic unregistration on halt (on shut down).
     # So the box will unregister only on destroy.
     config.registration.unregister_on_halt = false
     # disable auto-attach this will be provisioner task.
     config.registration.auto_attach = false
  end

  # Disabling the default /vagrant share
  config.vm.synced_folder ".", "/vagrant", disabled: true

  N = (vagrant_producers_config['num_nodes']).to_i

  (1..N).each do |i|
    vm_name = "producer-node#{i}"
    vm_memory = vagrant_producers_config['node_memory']

    config.vm.define "#{vm_name}" do |node|
      node.vm.hostname = "#{vm_name}"
      node.vm.provider :libvirt do |domain|
        domain.uri = 'qemu+unix:///system'
        domain.driver = 'kvm'
        domain.memory = "#{vm_memory}".to_i
        domain.cpus = 1
      end

      # The Ansible provisioner is executed on every node
      # The inventory file is re-created on each run.
      # FIXME: workers hosts must be a pattern. This
      # only works in Vagrant +1.8.0
      node.vm.provision :ansible do |ansible|
        ansible.groups = {
          "producers-group" => ["producer-node1", "producer-node2"],
          "all_groups:children" => ["producers-group"]
        }
        ansible.playbook = "provisioning/site.yml"
      end
    end
  end 
end
