# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# Require a recent version of vagrant otherwise some have reported errors 
# setting host names on boxes
Vagrant.require_version ">= 1.7.2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    vagrant_spark_config = {
        "num_nodes" => ENV['SPARK_NUM_NODES'] || 2,
	"box_name"  => "centos/7",
    }

    config.vm.box = vagrant_spark_config['box_name']

    # The number of Apache Spark nodes to provision.
    num_nodes = (vagrant_spark_config['num_nodes']).to_i

    num_nodes.times do |i|
      config.vm.define "spark_vm#{i}" do |node|
        node.vm.hostname = "spark-node0#{i}"
        config.vm.provider :libvirt do |domain|
	  domain.uri = 'qemu+unix:///system'
          domain.driver = 'kvm'
          domain.memory = 512
          domain.cpus = 1
        end
      end
    end

    #config.vm.provision "ansible" do |ansible|
    #  ansible.playbook = "provision/playbook.yml"
    #end

end
