---
# - Plays are map roles to hosts.  
# - Roles are just abstractions around tasks
# - Each "hosts:"-block (a play) will be executed 
#   one by one. So you can use multiple
#   blocks to force the desired execution order.
# - The plays are executed from top to down order.
# - Multiple roles declarations per play are executed
#   non in special order, you cannot control the order
#   of roles within a play.

# Play 0
- hosts: all
  roles:
   - common

# Play 1
- hosts: external
  roles:
   - external

# Play 2
- hosts: bootstrap 
  roles:
   - bootstrap

# Play 3
- hosts: dcos-masters
  roles:
   - masters

# Play 4
- hosts: dcos-agents-private
  roles:
   - agents-private

# Play 5
- hosts: dcos-agents-public
  roles:
   - agents-public
