# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

    config.vm.box = "centos/7"

    (1..4).each do |i|
      config.vm.define "k8s_vm#{i}" do |node|
        node.vm.hostname = "ks8-node0#{i}"
        config.vm.provider :libvirt do |domain|
	  domain.uri = 'qemu+unix:///system'
          domain.driver = 'kvm'
          domain.memory = 512
          domain.cpus = 1
        end
      end
    end

    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision/playbook.yml"
    end

end
