# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos-7"
  config.vm.box_url = "http://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-1605_01.LibVirt.box"
  config.vm.hostname = "docker-testbed"

  config.vm.define :docker_testbed do |docker_testbed|
    docker_testbed.vm.box = "centos-7"

    docker_testbed.vm.provider :libvirt do |domain|
      domain.memory = 4096
      domain.cpus = 2
      domain.nested = true
    end

  end

end

