---
- name: ext
  type: external
  box: centos/7
  ip: 103.0.10.99
  mem: 2048
  cpu: 2
- name: bt
  type: bootstrap
  box: centos/7
  ip: 103.0.10.100
  mem: 2048
  cpu: 2
- name: m1
  type: master
  box: centos/7
  ip: 103.0.10.101
  mem: 2048
  cpu: 2
- name: m2
  type: master
  box: centos/7
  ip: 103.0.10.102
  mem: 2048
  cpu: 2
- name: m3
  type: master
  box: centos/7
  ip: 103.0.10.103
  mem: 2048
  cpu: 2
- name: a1
  type: agent-private
  box: centos/7
  ip: 103.0.10.104
  mem: 2048
  cpu: 2
- name: p1
  type: agent-public
  box: centos/7
  ip: 103.0.10.105
  mem: 2048
  cpu: 2
