source ./00-hostnames

cat <<! > hosts
127.0.0.1   mn localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
$IP_MN 	$HOST_MN $MN
$IP_LB  $HOST_LB $LB
$IP_LBREG  $HOST_LBREG $LBREG
$IP_MASTER1 $HOST_MASTER1 $MASTER1
$IP_MASTER2 $HOST_MASTER2 $MASTER2
$IP_MASTER3 $HOST_MASTER3 $MASTER3
$IP_REGISTRY1 $HOST_REGISTRY1 $REGISTRY1
$IP_REGISTRY2 $HOST_REGISTRY2 $REGISTRY2
$IP_REGISTRY3 $HOST_REGISTRY3 $REGISTRY3
$IP_NODE1  $HOST_NODE1 $NODE1
$IP_NODE2  $HOST_NODE2 $NODE2
$IP_NODE3  $HOST_NODE3 $NODE3
$IP_NODE4  $HOST_NODE4 $NODE4
$IP_NODE5  $HOST_NODE5 $NODE5
!



