# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|

    config.vm.box = "dliappis/centos7minlibvirt"

    (1..3).each do |i|
      config.vm.define "test_vm#{i}" do |node|
        config.vm.provider "libvirt" do |domain|
          domain.uri = 'qemu+unix:///system'
          domain.driver = 'kvm'
          domain.storage_pool_name = 'USB_VMs'
          domain.host = "test#{i}"
          domain.driver = "kvm"
          domain.memory = 512
          domain.cpus = 1
        end
      end
    end

end
