---
- name: Get Docker release tool key
  apt_key: keyserver={{docker_keyserver}} id={{docker_keyserver_id}} state=present

- name: Add Docker deb repository
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-{{docker_ubuntu_name}} main"
    state: "present"
    update_cache: yes

- name: Get kernel version
  command: uname -r
  register: docker_kernel_version
  changed_when: False

- name: Install linux-image-extra-$(uname -r)
  apt:
    name: "linux-image-extra-{{docker_kernel_version.stdout}}"
    state: "present"

# Install fixed version (http://www.ubuntuupdates.org/ppa/docker_new)
- name: Install Docker
  apt:
    name: "docker-engine={{docker_version}}-0~{{docker_ubuntu_name}}"
    state: "present"

- name: Create /var/marathon
  file: path=/var/marathon/  state=directory

- name: Set docker daemon options
  copy:
    content: "DOCKER_OPTS=\"{{ docker_opts }}\""
    dest: /etc/default/docker
    owner: root
    group: root
    mode: 0644
  when: docker_opts != ""

- name: Add env file to Systemd config
  lineinfile:
    dest: /lib/systemd/system/docker.service
    insertafter: '^\[Service\]'
    line: "EnvironmentFile=/etc/default/docker"
    state: present
  register: docker_conf_updated_env

- name: Change docker command to run with DOCKER_OPTS
  lineinfile:
    dest: /lib/systemd/system/docker.service
    regexp: "^ExecStart"
    line: "ExecStart=/usr/bin/docker -d -H fd:// $DOCKER_OPTS"
    state: present
  register: docker_conf_updated_opts

- name: Reload systemd immediately ## https://github.com/ansible/ansible-modules-core/issues/191
  sudo: yes
  command: systemctl daemon-reload
  when: docker_conf_updated_env.changed or docker_conf_updated_opts.changed

- name: Restart docker immediately
  service: name=docker state=restarted
  when: docker_conf_updated_env.changed or docker_conf_updated_opts.changed

