---
- name: mesos-master1
  box: centos/7
  ip: 100.0.10.11
  mem: 1024
- name: mesos-slave1
  box: centos/7
  ip: 100.0.10.101
  mem: 1024
- name: mesos-slave2
  box: centos/7
  ip: 100.0.10.102
  mem: 1024

