---
- hosts: bootstrap 
  roles:
   - common
   - bootstrap

- hosts: dcos-masters
  roles:
   - common
   - masters

- hosts: dcos-agents-private
  roles:
   - common
   - agents-public

- hosts: dcos-agents-public
  roles:
   - common
   - agents-private
